services:
  scoreservice:
    build:
      context: .  # Assuming the Dockerfile is in the root of the project
    volumes:
      - .:/app  # Mount the current directory as /app in the container
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USER_NAME: ${USER_NAME}
      GAME_CHOICE: ${GAME_CHOICE}
      DIFFICULTY_LEVEL: ${DIFFICULTY_LEVEL}
      MEMORY_GAME_USER_LIST: ${MEMORY_GAME_USER_LIST}
      USER_GUESS: ${USER_GUESS}
    depends_on:
      - scoresdata  # Ensure scoresdata starts before scoreservice

  scoresdata:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-loader:
    image: python:3.11-slim  # Use the same Python image as scoreservice
    volumes:
      - ./:/app  # Mount the current directory (including Scores.txt) as /app
    command: ["python", "data_loading_script.py"]  # Replace with your data loading script

volumes:
  scoresdata:

