name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t tannvi/project .
          docker push tannvi/project

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for the application to start
        run: |
          max_retries=10
          retry_count=0
          until [ $(curl -s -o /dev/null -w '%{http_code}' http://localhost:5000) -eq 200 ]; do
            if [ $retry_count -eq $max_retries ]; then
              echo "Application failed to start within the timeout period"
              docker-compose logs
              exit 1
            fi
            echo "Waiting for application to start..."
            sleep 5
            retry_count=$((retry_count+1))
          done

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python tests/e2e.py http://localhost:5000

      - name: Cleanup
        run: docker-compose down

